apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-cm
data:
  PUID: "1000"
  PGID: "1000"
  PORT: "8211" # Optional but recommended
  PLAYERS: "16" # Optional but recommended
  MULTITHREADING: "true"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  COMMUNITY: "false"  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
  # Enable the environment variables below if you have COMMUNITY=true
  # SERVER_PASSWORD: "yourServerPassword"
  SERVER_NAME: "Server_Name" # Note, it seems spaces are not supported, so use underlines.